services:
  gelection:
    image: george124816/gelection:latest
    ports:
      - target: 4000
        published: 5000
        protocol: tcp
        mode: ingress
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SSL_MODE=${DATABASE_SSL_MODE}
      - OTEL_HOST=${OTEL_HOST}
      - OTEL_PORT=${OTEL_PORT}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
