services:
  generator:
    image: george124816/gelection:latest
    ports:
      - target: 4000
        published: 5000
        protocol: tcp
        mode: ingress
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_USER=${secrets.DATABASE_USER}
      - DATABASE_PASSWORD=${secrets.DATABASE_PASSWORD}
      - DATABASE_HOST=${secrets.DATABASE_HOST}
      - DATABASE_PORT=${secrets.DATABASE_PORT}
      - DATABASE_NAME=${secrets.DATABASE_NAME}
      - DATABASE_SSL_MODE=${secrets.DATABASE_SSL_MODE}
      - OTEL_HOST=${secrets.OTEL_HOST}
      - OTEL_PORT=${secrets.OTEL_PORT}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
