name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t gelection .

      - name: Stop container
        run: docker stop gelection

      - name: Remove previous version
        run: docker rm gelection

      - name: Run the server
        run: docker run -p 5000:4000 -d -e POSTGRES_URL=$POSTGRES_URL --name gelection --restart unless-stopped gelection
