name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - chore/create-workflow-pipeline

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TestHelloWorld
        run: mkdir "crazy_things_happim"
        
