name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_SSL_MODE: ${{ secrets.DATABASE_SSL_MODE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t gelection .

      - name: Stop container
        run: docker stop gelection

      - name: Remove previous version
        run: docker rm gelection

      - name: Run the server
        run: docker run -p 5000:4000 -d -e DATABASE_USER=$DATABASE_USER \
        -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
        -e DATABASE_HOST=$DATABASE_HOST \
        -e DATABASE_PORT=$DATABASE_PORT \
        -e DATABASE_NAME=$DATABASE_NAME \
        -e DATABASE_SSL_MODE=$DATABASE_SSL_MODE \
        --name gelection --restart unless-stopped gelection
