name: Validate CI

on:
  pull_request:

jobs:
  gofmt:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    container: node:20
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v2
