name: Validate CI

on:
  pull_request:

jobs:
  lintci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: actionlint
        uses: raven-actions/actionlint@v2
