name: Go Format

on:
  pull_request:

jobs:
  go_test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Run go fmt
        run: |
          FILES=$(gofmt -l .)
          if [ -n "$FILES" ]; then
            echo "The following files are not formatted:"
            echo "$FILES"
            echo "Run 'go fmt ./...' locally to fix."
            exit 1
          fi
