name: Go Test

on:
  pull_request:

jobs:
  gofmt:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Run gofmt
        run: |
          go test
